---

# This playbook installs applications

- hosts: service-server
  sudo: true
  vars_files:
    - "common/vars/main.yml"
  roles:
    - service

- hosts: update-server
  sudo: true
  vars_files:
    - "common/vars/main.yml"
  roles:
    - update
