---

# This playbook installs runtime dependencies and applications

- hosts: application-server
  sudo: true
  vars_files:
    - "common/vars/main.yml"
  roles:
    - base

- hosts: query-server
  sudo: true
  vars_files:
    - "common/vars/main.yml"
  roles:
    - query

- hosts: update-server
  sudo: true
  vars_files:
    - "common/vars/main.yml"
  roles:
    - update
