# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # specific log levels
  loggers:
    "fi.helsinki.koulutustarjonta": DEBUG

  appenders:
    - type: console
      threshold: ALL
      target: stdout

database:
  # the name of your JDBC driver
  driverClass: oracle.jdbc.OracleDriver

  # the username
  user: koultarj

  # the password
  password: koultarj

  # the JDBC URL
  url: jdbc:oracle:thin:@10.10.10.10:1521:XE

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* MyService Health Check */ SELECT 1 FROM dual"

  # the minimum number of connections to keep open
  minSize: 8

  # the maximum number of connections to keep open
  maxSize: 32

  # whether or not idle connections should be validated
  checkConnectionWhileIdle: false

  # log errors when connections fail validation
  logValidationErrors: true

  # the amount of time to sleep between runs of the idle connection validation, abandoned cleaner and idle pool resizing
  evictionInterval: 10s

  # the minimum amount of time an connection must sit idle in the pool before it is eligible for eviction
  minIdleTime: 1 minute

apiEndpoint: http://10.10.10.10:8080
