# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  appenders:
    - type: console


tarjontaClient:
  baseUrl: https://od.helsinki.fi/tarjonta-service/rest/v1/
